nano_user:
    resource: "@NanoUserBundle/Controller/"
    type:     annotation
    prefix:   /

nano_agora:
    resource: "@NanoAgoraBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
