<?php

namespace Nano\AgoraBundle\Repository;

/**
 * Evolution_maladieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Evolution_maladieRepository extends \Doctrine\ORM\EntityRepository
{
}
