<?php

namespace Nano\AgoraBundle\Repository;

/**
 * Examen_laboratoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Examen_laboratoireRepository extends \Doctrine\ORM\EntityRepository
{
}
