<?php

namespace Nano\AgoraBundle\Repository;

/**
 * HoraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoraireRepository extends \Doctrine\ORM\EntityRepository
{
}
