<?php

namespace Nano\AgoraBundle\Repository;

/**
 * LaboratoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaboratoireRepository extends \Doctrine\ORM\EntityRepository
{
}
