<?php

namespace Nano\AgoraBundle\Repository;

/**
 * rienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rienRepository extends \Doctrine\ORM\EntityRepository
{
}
