<?php

namespace Nano\AgoraBundle\Repository;

/**
 * Symptome_maladieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Symptome_maladieRepository extends \Doctrine\ORM\EntityRepository
{
}
