evolution_maladie_index:
    path:     /
    defaults: { _controller: "NanoAgoraBundle:Evolution_maladie:index" }
    methods:  GET

evolution_maladie_show:
    path:     /{id}/show
    defaults: { _controller: "NanoAgoraBundle:Evolution_maladie:show" }
    methods:  GET

evolution_maladie_new:
    path:     /new
    defaults: { _controller: "NanoAgoraBundle:Evolution_maladie:new" }
    methods:  [GET, POST]

evolution_maladie_edit:
    path:     /{id}/edit
    defaults: { _controller: "NanoAgoraBundle:Evolution_maladie:edit" }
    methods:  [GET, POST]

evolution_maladie_delete:
    path:     /{id}/delete
    defaults: { _controller: "NanoAgoraBundle:Evolution_maladie:delete" }
    methods:  DELETE
