medecin_index:
    path:     /
    defaults: { _controller: "NanoAgoraBundle:Medecin:index" }
    methods:  GET

medecin_show:
    path:     /{id}/show
    defaults: { _controller: "NanoAgoraBundle:Medecin:show" }
    methods:  GET

medecin_new:
    path:     /new
    defaults: { _controller: "NanoAgoraBundle:Medecin:new" }
    methods:  [GET, POST]

medecin_edit:
    path:     /{id}/edit
    defaults: { _controller: "NanoAgoraBundle:Medecin:edit" }
    methods:  [GET, POST]

medecin_delete:
    path:     /{id}/delete
    defaults: { _controller: "NanoAgoraBundle:Medecin:delete" }
    methods:  DELETE
