message_index:
    path:     /
    defaults: { _controller: "NanoAgoraBundle:Message:index" }
    methods:  GET

message_show:
    path:     /{id}/show
    defaults: { _controller: "NanoAgoraBundle:Message:show" }
    methods:  GET

message_new:
    path:     /new
    defaults: { _controller: "NanoAgoraBundle:Message:new" }
    methods:  [GET, POST]

message_edit:
    path:     /{id}/edit
    defaults: { _controller: "NanoAgoraBundle:Message:edit" }
    methods:  [GET, POST]

message_delete:
    path:     /{id}/delete
    defaults: { _controller: "NanoAgoraBundle:Message:delete" }
    methods:  DELETE
